// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mailgun

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-mailgun/sdk/v3/go/mailgun/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// `Domain` provides details about a Mailgun domain.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"fmt"
//
//	"github.com/pulumi/pulumi-aws/sdk/v7/go/aws"
//	"github.com/pulumi/pulumi-mailgun/sdk/v3/go/mailgun"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			domain, err := mailgun.GetDomain(ctx, &mailgun.LookupDomainArgs{
//				Name: "test.example.com",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = aws.NewRoute53Record(ctx, "mailgun-mx", &aws.Route53RecordArgs{
//				ZoneId: zoneId,
//				Name:   domainMailgun.Name,
//				Type:   "MX",
//				Ttl:    3600,
//				Records: []string{
//					fmt.Sprintf("%v %v.", domain.ReceivingRecords[0].Priority, domain.ReceivingRecords[0].Value),
//					fmt.Sprintf("%v %v.", domain.ReceivingRecords[1].Priority, domain.ReceivingRecords[1].Value),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupDomain(ctx *pulumi.Context, args *LookupDomainArgs, opts ...pulumi.InvokeOption) (*LookupDomainResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupDomainResult
	err := ctx.Invoke("mailgun:index/getDomain:getDomain", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDomain.
type LookupDomainArgs struct {
	// The name of the domain.
	Name string `pulumi:"name"`
	// The region where domain will be created. Default value is `us`.
	Region *string `pulumi:"region"`
}

// A collection of values returned by getDomain.
type LookupDomainResult struct {
	// The click tracking setting.
	ClickTracking      bool   `pulumi:"clickTracking"`
	DkimKeySize        int    `pulumi:"dkimKeySize"`
	DkimSelector       string `pulumi:"dkimSelector"`
	ForceDkimAuthority bool   `pulumi:"forceDkimAuthority"`
	Id                 string `pulumi:"id"`
	// The name of the record.
	Name string `pulumi:"name"`
	// The open tracking setting.
	OpenTracking         bool                           `pulumi:"openTracking"`
	ReceivingRecordsSets []GetDomainReceivingRecordsSet `pulumi:"receivingRecordsSets"`
	Region               string                         `pulumi:"region"`
	SendingRecordsSets   []GetDomainSendingRecordsSet   `pulumi:"sendingRecordsSets"`
	// The login email for the SMTP server.
	SmtpLogin string `pulumi:"smtpLogin"`
	// The password to the SMTP server.
	SmtpPassword string `pulumi:"smtpPassword"`
	// The spam filtering setting.
	SpamAction                 string `pulumi:"spamAction"`
	UseAutomaticSenderSecurity bool   `pulumi:"useAutomaticSenderSecurity"`
	// The tracking web scheme.
	WebScheme string `pulumi:"webScheme"`
	// Whether or not the domain will accept email for sub-domains.
	Wildcard bool `pulumi:"wildcard"`
}

func LookupDomainOutput(ctx *pulumi.Context, args LookupDomainOutputArgs, opts ...pulumi.InvokeOption) LookupDomainResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupDomainResultOutput, error) {
			args := v.(LookupDomainArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mailgun:index/getDomain:getDomain", args, LookupDomainResultOutput{}, options).(LookupDomainResultOutput), nil
		}).(LookupDomainResultOutput)
}

// A collection of arguments for invoking getDomain.
type LookupDomainOutputArgs struct {
	// The name of the domain.
	Name pulumi.StringInput `pulumi:"name"`
	// The region where domain will be created. Default value is `us`.
	Region pulumi.StringPtrInput `pulumi:"region"`
}

func (LookupDomainOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDomainArgs)(nil)).Elem()
}

// A collection of values returned by getDomain.
type LookupDomainResultOutput struct{ *pulumi.OutputState }

func (LookupDomainResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDomainResult)(nil)).Elem()
}

func (o LookupDomainResultOutput) ToLookupDomainResultOutput() LookupDomainResultOutput {
	return o
}

func (o LookupDomainResultOutput) ToLookupDomainResultOutputWithContext(ctx context.Context) LookupDomainResultOutput {
	return o
}

// The click tracking setting.
func (o LookupDomainResultOutput) ClickTracking() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupDomainResult) bool { return v.ClickTracking }).(pulumi.BoolOutput)
}

func (o LookupDomainResultOutput) DkimKeySize() pulumi.IntOutput {
	return o.ApplyT(func(v LookupDomainResult) int { return v.DkimKeySize }).(pulumi.IntOutput)
}

func (o LookupDomainResultOutput) DkimSelector() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDomainResult) string { return v.DkimSelector }).(pulumi.StringOutput)
}

func (o LookupDomainResultOutput) ForceDkimAuthority() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupDomainResult) bool { return v.ForceDkimAuthority }).(pulumi.BoolOutput)
}

func (o LookupDomainResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDomainResult) string { return v.Id }).(pulumi.StringOutput)
}

// The name of the record.
func (o LookupDomainResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDomainResult) string { return v.Name }).(pulumi.StringOutput)
}

// The open tracking setting.
func (o LookupDomainResultOutput) OpenTracking() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupDomainResult) bool { return v.OpenTracking }).(pulumi.BoolOutput)
}

func (o LookupDomainResultOutput) ReceivingRecordsSets() GetDomainReceivingRecordsSetArrayOutput {
	return o.ApplyT(func(v LookupDomainResult) []GetDomainReceivingRecordsSet { return v.ReceivingRecordsSets }).(GetDomainReceivingRecordsSetArrayOutput)
}

func (o LookupDomainResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDomainResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o LookupDomainResultOutput) SendingRecordsSets() GetDomainSendingRecordsSetArrayOutput {
	return o.ApplyT(func(v LookupDomainResult) []GetDomainSendingRecordsSet { return v.SendingRecordsSets }).(GetDomainSendingRecordsSetArrayOutput)
}

// The login email for the SMTP server.
func (o LookupDomainResultOutput) SmtpLogin() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDomainResult) string { return v.SmtpLogin }).(pulumi.StringOutput)
}

// The password to the SMTP server.
func (o LookupDomainResultOutput) SmtpPassword() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDomainResult) string { return v.SmtpPassword }).(pulumi.StringOutput)
}

// The spam filtering setting.
func (o LookupDomainResultOutput) SpamAction() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDomainResult) string { return v.SpamAction }).(pulumi.StringOutput)
}

func (o LookupDomainResultOutput) UseAutomaticSenderSecurity() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupDomainResult) bool { return v.UseAutomaticSenderSecurity }).(pulumi.BoolOutput)
}

// The tracking web scheme.
func (o LookupDomainResultOutput) WebScheme() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDomainResult) string { return v.WebScheme }).(pulumi.StringOutput)
}

// Whether or not the domain will accept email for sub-domains.
func (o LookupDomainResultOutput) Wildcard() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupDomainResult) bool { return v.Wildcard }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDomainResultOutput{})
}
