# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

SNAKE_TO_CAMEL_CASE_TABLE = {
    "api_key": "apiKey",
    "receiving_records": "receivingRecords",
    "sending_records": "sendingRecords",
    "smtp_login": "smtpLogin",
    "smtp_password": "smtpPassword",
    "spam_action": "spamAction",
}

CAMEL_TO_SNAKE_CASE_TABLE = {
    "apiKey": "api_key",
    "receivingRecords": "receiving_records",
    "sendingRecords": "sending_records",
    "smtpLogin": "smtp_login",
    "smtpPassword": "smtp_password",
    "spamAction": "spam_action",
}
