// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.mailgun.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.mailgun.outputs.GetDomainReceivingRecordsSet;
import com.pulumi.mailgun.outputs.GetDomainSendingRecordsSet;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetDomainResult {
    /**
     * @return The click tracking setting.
     * 
     */
    private Boolean clickTracking;
    private Integer dkimKeySize;
    private String dkimSelector;
    private Boolean forceDkimAuthority;
    private String id;
    /**
     * @return The name of the record.
     * 
     */
    private String name;
    /**
     * @return The open tracking setting.
     * 
     */
    private Boolean openTracking;
    private List<GetDomainReceivingRecordsSet> receivingRecordsSets;
    private String region;
    private List<GetDomainSendingRecordsSet> sendingRecordsSets;
    /**
     * @return The login email for the SMTP server.
     * 
     */
    private String smtpLogin;
    /**
     * @return The password to the SMTP server.
     * 
     */
    private String smtpPassword;
    /**
     * @return The spam filtering setting.
     * 
     */
    private String spamAction;
    private Boolean useAutomaticSenderSecurity;
    /**
     * @return The tracking web scheme.
     * 
     */
    private String webScheme;
    /**
     * @return Whether or not the domain will accept email for sub-domains.
     * 
     */
    private Boolean wildcard;

    private GetDomainResult() {}
    /**
     * @return The click tracking setting.
     * 
     */
    public Boolean clickTracking() {
        return this.clickTracking;
    }
    public Integer dkimKeySize() {
        return this.dkimKeySize;
    }
    public String dkimSelector() {
        return this.dkimSelector;
    }
    public Boolean forceDkimAuthority() {
        return this.forceDkimAuthority;
    }
    public String id() {
        return this.id;
    }
    /**
     * @return The name of the record.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The open tracking setting.
     * 
     */
    public Boolean openTracking() {
        return this.openTracking;
    }
    public List<GetDomainReceivingRecordsSet> receivingRecordsSets() {
        return this.receivingRecordsSets;
    }
    public String region() {
        return this.region;
    }
    public List<GetDomainSendingRecordsSet> sendingRecordsSets() {
        return this.sendingRecordsSets;
    }
    /**
     * @return The login email for the SMTP server.
     * 
     */
    public String smtpLogin() {
        return this.smtpLogin;
    }
    /**
     * @return The password to the SMTP server.
     * 
     */
    public String smtpPassword() {
        return this.smtpPassword;
    }
    /**
     * @return The spam filtering setting.
     * 
     */
    public String spamAction() {
        return this.spamAction;
    }
    public Boolean useAutomaticSenderSecurity() {
        return this.useAutomaticSenderSecurity;
    }
    /**
     * @return The tracking web scheme.
     * 
     */
    public String webScheme() {
        return this.webScheme;
    }
    /**
     * @return Whether or not the domain will accept email for sub-domains.
     * 
     */
    public Boolean wildcard() {
        return this.wildcard;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDomainResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean clickTracking;
        private Integer dkimKeySize;
        private String dkimSelector;
        private Boolean forceDkimAuthority;
        private String id;
        private String name;
        private Boolean openTracking;
        private List<GetDomainReceivingRecordsSet> receivingRecordsSets;
        private String region;
        private List<GetDomainSendingRecordsSet> sendingRecordsSets;
        private String smtpLogin;
        private String smtpPassword;
        private String spamAction;
        private Boolean useAutomaticSenderSecurity;
        private String webScheme;
        private Boolean wildcard;
        public Builder() {}
        public Builder(GetDomainResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.clickTracking = defaults.clickTracking;
    	      this.dkimKeySize = defaults.dkimKeySize;
    	      this.dkimSelector = defaults.dkimSelector;
    	      this.forceDkimAuthority = defaults.forceDkimAuthority;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.openTracking = defaults.openTracking;
    	      this.receivingRecordsSets = defaults.receivingRecordsSets;
    	      this.region = defaults.region;
    	      this.sendingRecordsSets = defaults.sendingRecordsSets;
    	      this.smtpLogin = defaults.smtpLogin;
    	      this.smtpPassword = defaults.smtpPassword;
    	      this.spamAction = defaults.spamAction;
    	      this.useAutomaticSenderSecurity = defaults.useAutomaticSenderSecurity;
    	      this.webScheme = defaults.webScheme;
    	      this.wildcard = defaults.wildcard;
        }

        @CustomType.Setter
        public Builder clickTracking(Boolean clickTracking) {
            if (clickTracking == null) {
              throw new MissingRequiredPropertyException("GetDomainResult", "clickTracking");
            }
            this.clickTracking = clickTracking;
            return this;
        }
        @CustomType.Setter
        public Builder dkimKeySize(Integer dkimKeySize) {
            if (dkimKeySize == null) {
              throw new MissingRequiredPropertyException("GetDomainResult", "dkimKeySize");
            }
            this.dkimKeySize = dkimKeySize;
            return this;
        }
        @CustomType.Setter
        public Builder dkimSelector(String dkimSelector) {
            if (dkimSelector == null) {
              throw new MissingRequiredPropertyException("GetDomainResult", "dkimSelector");
            }
            this.dkimSelector = dkimSelector;
            return this;
        }
        @CustomType.Setter
        public Builder forceDkimAuthority(Boolean forceDkimAuthority) {
            if (forceDkimAuthority == null) {
              throw new MissingRequiredPropertyException("GetDomainResult", "forceDkimAuthority");
            }
            this.forceDkimAuthority = forceDkimAuthority;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetDomainResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetDomainResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder openTracking(Boolean openTracking) {
            if (openTracking == null) {
              throw new MissingRequiredPropertyException("GetDomainResult", "openTracking");
            }
            this.openTracking = openTracking;
            return this;
        }
        @CustomType.Setter
        public Builder receivingRecordsSets(List<GetDomainReceivingRecordsSet> receivingRecordsSets) {
            if (receivingRecordsSets == null) {
              throw new MissingRequiredPropertyException("GetDomainResult", "receivingRecordsSets");
            }
            this.receivingRecordsSets = receivingRecordsSets;
            return this;
        }
        public Builder receivingRecordsSets(GetDomainReceivingRecordsSet... receivingRecordsSets) {
            return receivingRecordsSets(List.of(receivingRecordsSets));
        }
        @CustomType.Setter
        public Builder region(String region) {
            if (region == null) {
              throw new MissingRequiredPropertyException("GetDomainResult", "region");
            }
            this.region = region;
            return this;
        }
        @CustomType.Setter
        public Builder sendingRecordsSets(List<GetDomainSendingRecordsSet> sendingRecordsSets) {
            if (sendingRecordsSets == null) {
              throw new MissingRequiredPropertyException("GetDomainResult", "sendingRecordsSets");
            }
            this.sendingRecordsSets = sendingRecordsSets;
            return this;
        }
        public Builder sendingRecordsSets(GetDomainSendingRecordsSet... sendingRecordsSets) {
            return sendingRecordsSets(List.of(sendingRecordsSets));
        }
        @CustomType.Setter
        public Builder smtpLogin(String smtpLogin) {
            if (smtpLogin == null) {
              throw new MissingRequiredPropertyException("GetDomainResult", "smtpLogin");
            }
            this.smtpLogin = smtpLogin;
            return this;
        }
        @CustomType.Setter
        public Builder smtpPassword(String smtpPassword) {
            if (smtpPassword == null) {
              throw new MissingRequiredPropertyException("GetDomainResult", "smtpPassword");
            }
            this.smtpPassword = smtpPassword;
            return this;
        }
        @CustomType.Setter
        public Builder spamAction(String spamAction) {
            if (spamAction == null) {
              throw new MissingRequiredPropertyException("GetDomainResult", "spamAction");
            }
            this.spamAction = spamAction;
            return this;
        }
        @CustomType.Setter
        public Builder useAutomaticSenderSecurity(Boolean useAutomaticSenderSecurity) {
            if (useAutomaticSenderSecurity == null) {
              throw new MissingRequiredPropertyException("GetDomainResult", "useAutomaticSenderSecurity");
            }
            this.useAutomaticSenderSecurity = useAutomaticSenderSecurity;
            return this;
        }
        @CustomType.Setter
        public Builder webScheme(String webScheme) {
            if (webScheme == null) {
              throw new MissingRequiredPropertyException("GetDomainResult", "webScheme");
            }
            this.webScheme = webScheme;
            return this;
        }
        @CustomType.Setter
        public Builder wildcard(Boolean wildcard) {
            if (wildcard == null) {
              throw new MissingRequiredPropertyException("GetDomainResult", "wildcard");
            }
            this.wildcard = wildcard;
            return this;
        }
        public GetDomainResult build() {
            final var _resultValue = new GetDomainResult();
            _resultValue.clickTracking = clickTracking;
            _resultValue.dkimKeySize = dkimKeySize;
            _resultValue.dkimSelector = dkimSelector;
            _resultValue.forceDkimAuthority = forceDkimAuthority;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.openTracking = openTracking;
            _resultValue.receivingRecordsSets = receivingRecordsSets;
            _resultValue.region = region;
            _resultValue.sendingRecordsSets = sendingRecordsSets;
            _resultValue.smtpLogin = smtpLogin;
            _resultValue.smtpPassword = smtpPassword;
            _resultValue.spamAction = spamAction;
            _resultValue.useAutomaticSenderSecurity = useAutomaticSenderSecurity;
            _resultValue.webScheme = webScheme;
            _resultValue.wildcard = wildcard;
            return _resultValue;
        }
    }
}
