// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface DomainReceivingRecordsSet {
    id?: pulumi.Input<string | undefined>;
    /**
     * The priority of the record.
     */
    priority?: pulumi.Input<string | undefined>;
    /**
     * The record type.
     */
    recordType?: pulumi.Input<string | undefined>;
    /**
     * `"valid"` if the record is valid.
     */
    valid?: pulumi.Input<string | undefined>;
    /**
     * The value of the record.
     */
    value?: pulumi.Input<string | undefined>;
}

export interface DomainSendingRecordsSet {
    id?: pulumi.Input<string | undefined>;
    /**
     * The domain to add to Mailgun
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The record type.
     */
    recordType?: pulumi.Input<string | undefined>;
    /**
     * `"valid"` if the record is valid.
     */
    valid?: pulumi.Input<string | undefined>;
    /**
     * The value of the record.
     */
    value?: pulumi.Input<string | undefined>;
}

