// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface DomainReceivingRecord {
    /**
     * The priority of the record.
     */
    priority: string;
    /**
     * The record type.
     */
    recordType: string;
    /**
     * `"valid"` if the record is valid.
     */
    valid: string;
    /**
     * The value of the record.
     */
    value: string;
}

export interface DomainSendingRecord {
    /**
     * The domain to add to Mailgun
     */
    name: string;
    /**
     * The record type.
     */
    recordType: string;
    /**
     * `"valid"` if the record is valid.
     */
    valid: string;
    /**
     * The value of the record.
     */
    value: string;
}
