// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * `mailgun.Domain` provides details about a Mailgun domain.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 * import * as mailgun from "@pulumi/mailgun";
 *
 * const domain = pulumi.output(mailgun.getDomain({
 *     name: "test.example.com",
 * }));
 * const mailgun_mx = new aws.route53.Record("mailgun-mx", {
 *     name: mailgun_domain.name,
 *     records: [
 *         pulumi.interpolate`${domain.receivingRecords[0].priority} ${domain.receivingRecords[0].value}.`,
 *         pulumi.interpolate`${domain.receivingRecords[1].priority} ${domain.receivingRecords[1].value}.`,
 *     ],
 *     ttl: 3600,
 *     type: "MX",
 *     zoneId: var_zone_id,
 * });
 * ```
 */
export function getDomain(args: GetDomainArgs, opts?: pulumi.InvokeOptions): Promise<GetDomainResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("mailgun:index/getDomain:getDomain", {
        "dkimKeySize": args.dkimKeySize,
        "dkimSelector": args.dkimSelector,
        "name": args.name,
        "region": args.region,
        "smtpPassword": args.smtpPassword,
        "spamAction": args.spamAction,
        "wildcard": args.wildcard,
    }, opts);
}

/**
 * A collection of arguments for invoking getDomain.
 */
export interface GetDomainArgs {
    dkimKeySize?: number;
    dkimSelector?: string;
    /**
     * The name of the domain.
     */
    name: string;
    region?: string;
    /**
     * The password to the SMTP server.
     */
    smtpPassword?: string;
    /**
     * The spam filtering setting.
     */
    spamAction?: string;
    /**
     * Whether or not the domain will accept email for sub-domains.
     */
    wildcard?: boolean;
}

/**
 * A collection of values returned by getDomain.
 */
export interface GetDomainResult {
    readonly dkimKeySize?: number;
    readonly dkimSelector?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The name of the record.
     */
    readonly name: string;
    /**
     * A list of DNS records for receiving validation.
     */
    readonly receivingRecords: outputs.GetDomainReceivingRecord[];
    readonly region?: string;
    /**
     * A list of DNS records for sending validation.
     */
    readonly sendingRecords: outputs.GetDomainSendingRecord[];
    /**
     * The login email for the SMTP server.
     */
    readonly smtpLogin: string;
    /**
     * The password to the SMTP server.
     */
    readonly smtpPassword: string;
    /**
     * The spam filtering setting.
     */
    readonly spamAction?: string;
    /**
     * Whether or not the domain will accept email for sub-domains.
     */
    readonly wildcard?: boolean;
}

export function getDomainOutput(args: GetDomainOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDomainResult> {
    return pulumi.output(args).apply(a => getDomain(a, opts))
}

/**
 * A collection of arguments for invoking getDomain.
 */
export interface GetDomainOutputArgs {
    dkimKeySize?: pulumi.Input<number>;
    dkimSelector?: pulumi.Input<string>;
    /**
     * The name of the domain.
     */
    name: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    /**
     * The password to the SMTP server.
     */
    smtpPassword?: pulumi.Input<string>;
    /**
     * The spam filtering setting.
     */
    spamAction?: pulumi.Input<string>;
    /**
     * Whether or not the domain will accept email for sub-domains.
     */
    wildcard?: pulumi.Input<boolean>;
}
